# Generated by Django 3.2 on 2023-09-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AutoSelectionTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=255, null=True)),
                ('dataset_id', models.BigIntegerField(blank=True, null=True)),
                ('metric_id', models.IntegerField(blank=True, null=True)),
                ('query_length', models.IntegerField(blank=True, null=True)),
                ('document_length', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('result_file', models.CharField(blank=True, max_length=255, null=True)),
                ('result_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auto_selection_task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sym', models.CharField(blank=True, max_length=1000, null=True)),
                ('photo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('dia_list', models.CharField(blank=True, max_length=1000, null=True)),
                ('annotation', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('dataset', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'ct_information',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtValidation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('patient_id', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('dia_list', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('bone_name', models.CharField(blank=True, max_length=255, null=True)),
                ('direction', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('dataset', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'ct_validation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.IntegerField()),
                ('link', models.CharField(blank=True, max_length=300, null=True)),
                ('islabeled', models.CharField(blank=True, max_length=4, null=True)),
                ('test', models.IntegerField(blank=True, null=True)),
                ('valid', models.IntegerField(blank=True, null=True)),
                ('train', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dataset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataSetsUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=255)),
                ('dataset_desc', models.CharField(max_length=255)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('train_path', models.CharField(blank=True, max_length=255, null=True)),
                ('train_name', models.CharField(blank=True, max_length=255, null=True)),
                ('test_path', models.CharField(blank=True, max_length=255, null=True)),
                ('test_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dev_path', models.CharField(blank=True, max_length=255, null=True)),
                ('dev_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'data_sets_upload',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeepModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('model_introduction', models.TextField(blank=True, null=True)),
                ('model_article_title', models.CharField(blank=True, max_length=255, null=True)),
                ('model_article_url', models.CharField(blank=True, max_length=255, null=True)),
                ('model_architecture_url', models.CharField(blank=True, max_length=255, null=True)),
                ('model_code_url', models.CharField(blank=True, max_length=255, null=True)),
                ('config_file', models.CharField(blank=True, max_length=255, null=True)),
                ('model_py', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'deep_model',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeepModelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'deep_model_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeepModelMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'deep_model_metric',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeepModelTaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(blank=True, null=True)),
                ('model_id', models.BigIntegerField(blank=True, null=True)),
                ('ndcg_1', models.CharField(blank=True, db_column='ndcg@1', max_length=255, null=True)),
                ('ndcg_3', models.CharField(blank=True, db_column='ndcg@3', max_length=255, null=True)),
                ('ndcg_5', models.CharField(blank=True, db_column='ndcg@5', max_length=255, null=True)),
                ('ndcg_10', models.CharField(blank=True, db_column='ndcg@10', max_length=255, null=True)),
                ('map', models.CharField(blank=True, max_length=255, null=True)),
                ('recall_3', models.CharField(blank=True, db_column='recall@3', max_length=255, null=True)),
                ('recall_5', models.CharField(blank=True, db_column='recall@5', max_length=255, null=True)),
                ('recall_10', models.CharField(blank=True, db_column='recall@10', max_length=255, null=True)),
                ('pre_1', models.CharField(blank=True, db_column='pre@1', max_length=255, null=True)),
                ('pre_3', models.CharField(blank=True, db_column='pre@3', max_length=255, null=True)),
                ('pre_5', models.CharField(blank=True, db_column='pre@5', max_length=255, null=True)),
                ('pre_10', models.CharField(blank=True, db_column='pre@10', max_length=255, null=True)),
            ],
            options={
                'db_table': 'deep_model_task_result',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('hdid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('identityid', models.CharField(db_column='identityID', max_length=18)),
                ('birthday', models.CharField(blank=True, max_length=10, null=True)),
                ('marriage', models.CharField(blank=True, max_length=2, null=True)),
                ('nation', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=30, null=True)),
                ('work_place', models.CharField(blank=True, max_length=30, null=True)),
                ('entry_time', models.CharField(blank=True, max_length=10, null=True)),
                ('department', models.BigIntegerField(blank=True, null=True)),
                ('duty', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('skill', models.CharField(blank=True, max_length=500, null=True)),
                ('outpatient_time', models.CharField(blank=True, max_length=500, null=True)),
                ('introduction', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'doctor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_id', models.IntegerField()),
                ('doctor_diagnosis', models.CharField(blank=True, max_length=16384, null=True)),
            ],
            options={
                'db_table': 'doctor_diagnosis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('identityid', models.CharField(db_column='identityID', max_length=255)),
                ('birthday', models.CharField(blank=True, max_length=10, null=True)),
                ('marriage', models.CharField(blank=True, max_length=4, null=True)),
                ('nation', models.CharField(blank=True, max_length=25, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=50, null=True)),
                ('work_place', models.CharField(blank=True, max_length=50, null=True)),
                ('education', models.CharField(blank=True, max_length=250, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('skill', models.CharField(blank=True, max_length=250, null=True)),
                ('introduction', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'expert',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg_name', models.CharField(blank=True, max_length=255, null=True)),
                ('kg_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'kg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgUpload',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('kg_desc', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'kg_upload',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KnowledgeEmbeddingExplorationTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=255, null=True)),
                ('dataset_id', models.BigIntegerField(blank=True, null=True)),
                ('metric_id', models.BigIntegerField(blank=True, null=True)),
                ('query_length', models.IntegerField(blank=True, null=True)),
                ('document_length', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('result_id', models.BigIntegerField(blank=True, null=True)),
                ('result_file', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'knowledge_embedding_exploration_task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalArchive',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('zip_file_path', models.CharField(max_length=255)),
                ('txt_file_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'medical_archive',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelEvaluationTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('dataset_id', models.IntegerField(blank=True, null=True)),
                ('query_length', models.IntegerField(blank=True, null=True)),
                ('document_length', models.IntegerField(blank=True, null=True)),
                ('model_id', models.IntegerField(blank=True, null=True)),
                ('metric_id', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('result_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'model_evaluation_task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('birthday', models.CharField(blank=True, max_length=10, null=True)),
                ('marriage', models.CharField(blank=True, max_length=2, null=True)),
                ('nation', models.CharField(blank=True, max_length=30, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=30, null=True)),
                ('work_place', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=11, null=True)),
                ('contact_relationship', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_address', models.CharField(blank=True, max_length=30, null=True)),
                ('category', models.CharField(blank=True, max_length=30, null=True)),
                ('medicare_card_id', models.CharField(blank=True, max_length=15, null=True)),
                ('identityid', models.CharField(db_column='identityID', max_length=18)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resource', models.CharField(db_collation='utf8mb3_general_ci', max_length=50)),
                ('url', models.CharField(db_collation='utf8mb3_general_ci', max_length=256)),
                ('handle', models.CharField(db_collation='utf8mb3_general_ci', max_length=20)),
            ],
            options={
                'db_table': 'permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qid', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('hospitaldepartmentid', models.BigIntegerField(db_column='hospitalDepartmentId')),
                ('type', models.IntegerField()),
                ('userid', models.BigIntegerField()),
                ('remark', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionDetailAnswer',
            fields=[
                ('qrid', models.BigAutoField(primary_key=True, serialize=False)),
                ('qid', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('detail_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'question_detail_answer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questionresult',
            fields=[
                ('qrid', models.BigAutoField(primary_key=True, serialize=False)),
                ('resulttype', models.IntegerField(blank=True, db_column='resultType', null=True)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'questionresult',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('hospitaldepartmentid', models.IntegerField(blank=True, db_column='hospitalDepartmentId', null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'question_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=10, null=True)),
                ('data', models.CharField(blank=True, max_length=20, null=True)),
                ('savepath', models.CharField(blank=True, max_length=256, null=True)),
                ('prec', models.IntegerField(blank=True, null=True)),
                ('recall', models.IntegerField(blank=True, null=True)),
                ('f1', models.IntegerField(blank=True, null=True)),
                ('classification', models.CharField(blank=True, max_length=50, null=True)),
                ('epoch', models.IntegerField(blank=True, null=True)),
                ('batchsize', models.IntegerField(blank=True, null=True)),
                ('rnn_cell', models.CharField(blank=True, max_length=20, null=True)),
                ('embedding', models.CharField(blank=True, max_length=20, null=True)),
                ('bleu', models.FloatField(blank=True, null=True)),
                ('deleted', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='utf8mb3_general_ci', max_length=20)),
            ],
            options={
                'db_table': 'role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role_id', models.BigIntegerField()),
                ('permission_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'role_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SimilarGraphs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kgid', models.IntegerField(db_column='kgId')),
                ('similar_graphs', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'similar_graphs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('login_name', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('phone', models.CharField(blank=True, max_length=18, null=True)),
                ('type', models.IntegerField()),
                ('state', models.TextField()),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('picture', models.CharField(blank=True, max_length=50, null=True)),
                ('identityid', models.CharField(db_column='identityID', max_length=18)),
                ('birthday', models.CharField(blank=True, max_length=10, null=True)),
                ('nation', models.CharField(blank=True, max_length=50, null=True)),
                ('marriage', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=50, null=True)),
                ('work_place', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'sys_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskResultEvaluationTemp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_id', models.IntegerField(blank=True, null=True)),
                ('model_id', models.BigIntegerField(blank=True, null=True)),
                ('map', models.CharField(blank=True, max_length=255, null=True)),
                ('p_3', models.CharField(blank=True, db_column='p@3', max_length=255, null=True)),
                ('p_5', models.CharField(blank=True, db_column='p@5', max_length=255, null=True)),
                ('r_3', models.CharField(blank=True, db_column='r@3', max_length=255, null=True)),
                ('r_5', models.CharField(blank=True, db_column='r@5', max_length=255, null=True)),
                ('n_3', models.CharField(blank=True, db_column='n@3', max_length=255, null=True)),
                ('n_5', models.CharField(blank=True, db_column='n@5', max_length=255, null=True)),
            ],
            options={
                'db_table': 'task_result_evaluation_temp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskResultExplorationTemp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_id', models.IntegerField(blank=True, null=True)),
                ('model_id', models.BigIntegerField(blank=True, null=True)),
                ('map', models.CharField(blank=True, max_length=255, null=True)),
                ('p_3', models.CharField(blank=True, db_column='p@3', max_length=255, null=True)),
                ('p_5', models.CharField(blank=True, db_column='p@5', max_length=255, null=True)),
                ('r_3', models.CharField(blank=True, db_column='r@3', max_length=255, null=True)),
                ('r_5', models.CharField(blank=True, db_column='r@5', max_length=255, null=True)),
                ('n_3', models.CharField(blank=True, db_column='n@3', max_length=255, null=True)),
                ('n_5', models.CharField(blank=True, db_column='n@5', max_length=255, null=True)),
            ],
            options={
                'db_table': 'task_result_exploration_temp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskResultSelectionTemp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_id', models.IntegerField(blank=True, null=True)),
                ('model_id', models.BigIntegerField(blank=True, null=True)),
                ('map', models.CharField(blank=True, max_length=255, null=True)),
                ('p_3', models.CharField(blank=True, db_column='p@3', max_length=255, null=True)),
                ('p_5', models.CharField(blank=True, db_column='p@5', max_length=255, null=True)),
                ('r_3', models.CharField(blank=True, db_column='r@3', max_length=255, null=True)),
                ('r_5', models.CharField(blank=True, db_column='r@5', max_length=255, null=True)),
                ('n_3', models.CharField(blank=True, db_column='n@3', max_length=255, null=True)),
                ('n_5', models.CharField(blank=True, db_column='n@5', max_length=255, null=True)),
            ],
            options={
                'db_table': 'task_result_selection_temp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskResultTemp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_id', models.IntegerField(blank=True, null=True)),
                ('model_id', models.BigIntegerField(blank=True, null=True)),
                ('map', models.CharField(blank=True, max_length=255, null=True)),
                ('p_3', models.CharField(blank=True, db_column='p@3', max_length=255, null=True)),
                ('p_5', models.CharField(blank=True, db_column='p@5', max_length=255, null=True)),
                ('r_3', models.CharField(blank=True, db_column='r@3', max_length=255, null=True)),
                ('r_5', models.CharField(blank=True, db_column='r@5', max_length=255, null=True)),
                ('n_3', models.CharField(blank=True, db_column='n@3', max_length=255, null=True)),
                ('n_5', models.CharField(blank=True, db_column='n@5', max_length=255, null=True)),
            ],
            options={
                'db_table': 'task_result_temp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('role_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'user_role',
                'managed': False,
            },
        ),
    ]
