# Generated by Django 3.2 on 2023-09-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userrole',
            table='user_role',
        ),
    ]
