# Generated by Django 3.2 on 2023-09-02 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vqa', '0002_auto_20230902_1526'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authgroup',
            table='auth_group',
        ),
    ]
